class Feature:
    spanish_alliteration = {
        "ca": ["ca", ""],
        "co": ["co", ""],
        "cu": ["cu", ""],
        "c" + chr(225): ["c" + chr(225), ""],
        "c" + chr(243): ["c" + chr(243), ""],
        "c" + chr(250): ["c" + chr(250), ""],
        "q": ["q", ""],
        "k": ["k", ""],
        "p": ["p", ""],
        "m": ["m", ""],
        "nm": ["nm", ""],
        "nb": ["nb", ""],
        "np": ["np", ""],
        "rr": ["rr", ""],
        "r": ["r", ""],
        "ll": ["ll", ""],
        "l": ["l", ""],
        "s": ["s", ""],
        "t": ["t", ""],
        "f": ["f", ""],
        "c": ["c", ""],
        "b": ["b", ""],
        "v": ["v", ""],
        "d": ["d", ""],
        "cce": ["cce", ""],
        "cci": ["cci", ""],
        "cc" + chr(233): ["cc" + chr(233), ""],
        "cc" + chr(237): ["cc" + chr(237), ""],
        "z": ["z", ""],
        "ce": ["ce", ""],
        "ci": ["ci", ""],
        "c" + chr(233): ["c" + chr(233), ""],
        "c" + chr(237): ["c" + chr(237), ""],
        "x": ["x", ""],
        "j": ["j", ""],
        "ge": ["ge", ""],
        "gi": ["gi", ""],
        "g" + chr(233): ["g" + chr(233), ""],
        "g" + chr(237): ["g" + chr(237), ""],
        "g": ["g", ""],
        "ng": ["ng", ""],
        "nk": ["nk", ""],
        "y": ["y", ""],
        chr(241): [chr(241), ""]
    }

    spanish_assonance = {
        "a": ["a", ""],
        "ha": ["ha", ""],
        "h" + chr(225): ["h" + chr(225), ""],
        chr(225): [chr(225), ""],
        "e": ["e", ""],
        "he": ["he", ""],
        chr(233): [chr(233), ""],
        "h" + chr(233): ["h" + chr(233), ""],
        "que": ["que", ""],
        "i": ["i", ""],
        chr(237):  [chr(237), ""],
        "hi": ["hi", ""],
        "h" + chr(237):  ["h" + chr(237), ""],
        "o": ["o", ""],
        "ho": ["ho", ""],
        chr(243): [chr(243), ""],
        "h" + chr(243): ["h" + chr(243), ""],
        "u": ["u", ""],
        chr(250): [chr(250), ""],
        chr(252):  [chr(252), ""],
        "ai": ["ai", ""],
        "hai": ["hai", ""],
        "ei": ["ei", ""],
        "oi": ["oi", ""],
        "hoi": ["hoi", ""],
        "uy": ["uy", ""],
        "huy": ["huy", ""],
        "au": ["au", ""],
        "hau": ["hau", ""],
        "eu": ["eu", ""],
        "heu": ["heu", ""],
        "ou": ["ou", ""],
        "hou": ["hou", ""],
        "ia": ["ia", ""],
        "hia": ["hia", ""],
        "ie": ["ie", ""],
        "hie": ["hie", ""],
        "io": ["io", ""],
        "hio": ["hio", ""],
        "iu": ["iu", ""],
        "hiu": ["hiu", ""],
        "ua": ["ua", ""],
        "hua": ["hua", ""],
        "ue": ["ue", ""],
        "hue": ["hue", ""],
        "ui": ["ui", ""],
        "hui": ["hui", ""],
        "uo": ["uo", ""],
        "huo": ["huo", ""],
        "i" + chr(225) + "i": ["i" + chr(225) + "i", ""],
        "hi" + chr(225) + "i": ["hi" + chr(225) + "i", ""],
        "i" + chr(233) + "i": ["i" + chr(233) + "i", ""],
        "hi" + chr(233) + "i": ["hi" + chr(233) + "i", ""],
        "u" + chr(225) + "i": ["u" + chr(225) + "i", ""],
        "hu" + chr(225) + "i": ["hu" + chr(225) + "i", ""],
        "u" + chr(233) + "i": ["u" + chr(233) + "i", ""],
        "hu" + chr(233) + "i": ["hu" + chr(233) + "i", ""],
    }

    #Подумать как в слове modem выделять только последнюю m
    franch_alliteration = {
        "b": ["b", ""],
        "g": ["g", "g$"],
        "c": ["c", "^banc$;^tronc$;^tabac$"],
        "k": ["k", ""],
        "ck": ["ck", ""],
        "q": ["q", ""],
        "x": ["x;deux_ans;trois_ans;six_ans;dix_ans", "x$;^ax;^ex;^"+chr(233)+"x;^ix;^ox;^ux;^yx"],
        "ch": ["chaos;chaotique;chaotiques;charadriformes;ch"+chr(233)+
                "nopode;chiasma;chiasme;chitine;chiton;chlamydia;chlamyde;"
                "chloasma;^chlor;choeur;cholagogue;^chol;^chor;chr"+chr(233)+"me;"
                "chr"+chr(233)+"stomathie;^chr"+chr(233)+"t;^christ;^chrom;^chron;^chrys;ichor;"
                "ichtyo"+chr(239)+"de;^icht;isch"+chr(233)+"mie;isochore;isochrone;isochronisme;isch"+chr(233)+"mique;"
                "ischiatique;ischion;loch;looch;mach;machaon;^machiavel;"
                "manich"+chr(233)+"isme;melchior;melchite;moloch;opodeldoch;^psych;spiroch"+chr(233)+"te;"
                "spiroch"+chr(233)+"tose;strychos;trachyte;trach"+chr(233)+"ite"
                "^trach"+chr(233)+"o;trachome;trochile;trochilid"+chr(233)+"s;trochiter;trochl"+chr(233)+"e;"
                "tylenchus", ""
               ],
        "d": ["d", "d$"],
        "f": ["f", ""],
        "ph": ["ph", ""],
        "gn": ["gn", ""],
        "j": ["j", ""],
        "ge": ["ge", ""],
        "gi": ["gi", ""],
        "gy": ["gy", ""],
        "l": ["l", ""],
        "ll": ["ll", ""],
        "ill": ["ill", ""],
        "ma": ["ma", ""],
        "me": ["me", ""],
        "mi": ["mi", ""],
        "mo": ["mo", ""],
        "mu": ["mu", ""],
        "my": ["my", ""],
        "m"+chr(233): ["m"+chr(233), ""],
        "m"+chr(232): ["m"+chr(232), ""],
        "m"+chr(234): ["m"+chr(234), ""],
        "m"+chr(226): ["m"+chr(226), ""],
        "m"+chr(244): ["m"+chr(244), ""],
        "m"+chr(238): ["m"+chr(238), ""],
        "m"+chr(251): ["m"+chr(251), ""],
        "m": ["idem$;chelem$;schelem$;tandem$;stem$;modem$;ibidem$;rem$;requiem$", ""],
        "na": ["na", ""],
        "ne": ["ne", ""],
        "ni": ["ni", ""],
        "no": ["no", ""],
        "nu": ["nu", ""],
        "ny": ["ny", ""],
        "n" + chr(233): ["n" + chr(233), ""],
        "n" + chr(232): ["n" + chr(232), ""],
        "n" + chr(234): ["n" + chr(234), ""],
        "n" + chr(226): ["n" + chr(226), ""],
        "n" + chr(244): ["n" + chr(244), ""],
        "n" + chr(238): ["n" + chr(238), ""],
        "n" + chr(251): ["n" + chr(251), ""],
        "n": ["rumen;cyclamen;larsen;lumen;volumen;golden;gluten;graben;gramen;groschen;germen", ""],
        "p": ["p", "p$"],
        "r": ["^fier$|^cher$|^mer$|^amer$|^hier$|^fer$|^hiver$|^vers$|^ber$|^blister$|^cancer$|^bunker$|^casher$|"
              "^boxer$|^canter$|^eider$|^enfer$|^" + chr(233) + "ther$|^gangster$|^jonkheer$|^magister$|^master$|^poker$|"
              "^springer$|^starter$|^super$|^trochiter$|^ver$|^vomer$|^weber$|^baby-boomer$|^bloomer$|^booster$|^boulder$|"
              "^broker$|^cluster$|^cracker$|^dealer$|^designer$|^dispatcher$|^dogger$|^driver$|^eye-liner$|^liner$|^putter$|"
              "^soccer$|^stayer$|^stop-over$|^tanker$|^trader$|^turn-over$|r\B", ""
              ],
        "s": ["s", "([a,e,o,y,i]s[a,e,o,y,i])|s$"],
        "ce": ["ce", ""],
        "c" + chr(233): ["c" + chr(233), ""],
        "c" + chr(232): ["c" + chr(232), ""],
        "c" + chr(8217) + "e": ["c" + chr(8217) + "e", ""],
        "c"+chr(8217)+chr(233): ["c"+chr(8217)+chr(233), ""],
        "ci": ["ci", ""],
        "cy": ["cy", ""],
        chr(231): [chr(231), ""],
        "t": ["t", "ts|t$"],
        "v": ["v", ""],
        "z": ["z", "z$"],
        "asa": ["asa", ""],
        "ase": ["ase", ""],
        "asi": ["asi", ""],
        "aso": ["aso", ""],
        "asu": ["asu", ""],
        "asy": ["asy", ""],
        "esa": ["esa", ""],
        chr(233)+"sa": [chr(233)+"sa", ""],
        "ese": ["ese", ""],
        chr(232)+"se": [chr(232)+"se", ""],
        "esi": ["esi", ""],
        chr(233)+"si": [chr(233)+"si", ""],
        "eso": ["eso", ""],
        chr(233)+"so": [chr(233)+"so", ""],
        "esu": ["esu", ""],
        chr(233)+"su": [chr(233)+"su", ""],
        "esy": ["esy", ""],
        chr(233)+"sy": [chr(233)+"sy", ""],
        "isa": ["isa", ""],
        "ise": ["ise", ""],
        "is"+chr(232): ["is"+chr(232), ""],
        "isi": ["isi", ""],
        "iso": ["iso", ""],
        "isu": ["isu", ""],
        "isy": ["isy", ""],
        "osa": ["osa", ""],
        "ose": ["ose", ""],
        chr(244)+"se": [chr(244)+"se", ""],
        "osi": ["osi", ""],
        "oso": ["oso", ""],
        "osu": ["osu", ""],
        "osy": ["osy", ""],
        "usa": ["usa", ""],
        "use": ["use", ""],
        "us"+chr(232): ["us"+chr(232), ""],
        "usi": ["usi", ""],
        "uso": ["uso", ""],
        "usu": ["usu", ""],
        "usy": ["usy", ""],
        "ysa": ["ysa", ""],
        "yse": ["yse", ""],
        "ysi": ["ysi", ""],
        "yso": ["yso", ""],
        "ysu": ["ysu", ""],
        "ysy": ["ysy", ""],
        "mes": ["^mes", ""],
        "tes": ["^tes", ""],
        "ses": ["^ses", ""],
        "ces": ["^ces", ""],
        "les": ["^les", ""],
        "des": ["^des", ""],
        "vous": ["^vous", ""],
        "nous": ["^nous", ""],
        "ils": ["ils_a;ils_e;ils_i;ils_o;ils_y;ils_" + chr(233) + ";ils_" + chr(232) + ";ils_"+chr(234)+";ils_" +
                chr(226)+";ils_"+chr(224), ""],
        #Все ont выделить или t
        "ont": ["ont_a;ont_e;ont_i;ont_o;ont_u;ont_y;ont_"+ chr(233) + ";ont_"+chr(234)+";ont_" +
                chr(226)+";ont_"+chr(238),""],
        "dans":["dans_un;dans_une",""],
        "sans":["sans_un;sans_une",""],
        "sous":["sous_un;sous_une",""],
        "chez":["chez_un;chez_une",""],
        "aux":["aux_a;aux_e;aux_i;aux_o;aux_y;aux_" + chr(233) + ";aux_" + chr(232) + ";aux_"+chr(234)+";aux_" +
                chr(226)+";aux_"+chr(224), ""]
        #Продолжить
    }

    franch_assonance = {
        "a":["a",""],
        chr(226):[chr(226),""],
        chr(224):[chr(224),""],
        chr(233):[chr(233),""],
        "er":["er$","mer;cher;amer;hiver;fer"],
        "les":["^les$",""],
        "des":["^des$",""],
        "mes":["^mes$",""],
        "tes":["^tes$",""],
        "ses":["^ses$",""],
        "ces":["^ces$",""],
        chr(232):[chr(232),""],
        chr(234):[chr(234),""],
        "ebb":["ebb",""],
        "ecc":["ecc",""],
        "edd":["edd",""],
        "eff":["eff",""],
        "egg":["egg",""],
        "ekk":["ekk",""],
        "ell":["ell",""],
        "emm":["emm",""],
        "enn":["enn",""],
        "epp":["epp",""],
        "err":["err",""],
        "ess":["ess",""],
        "ett":["ett",""],
        "ezz":["ezz",""],
        "ai":["ai",""],
        "et":["et$",""],
        "ei":["ei",""],
        "est":["^est$",""],
        "y":["y",""],
        "aill":["aill",""],
        "eill":["eill",""],
        "eu":["eu$",""],
        "eux":["eux$",""],
        "eut":["eut$",""],
        "euse":["euse",""],
        "oeu":["oeu$",""],
        "oeux":["oeux$",""],
        "oeut":["oeut$",""],
        "oeud":["oeud$",""],
        "u":["u","qu;gu"],
        chr(251):[chr(251),""],
        chr(251):[chr(251),""],
        "aur":["aur",""],
        "ose":["ose",""],
        "o":["o$",""],
        "os":["os$",""],
        "op":["op$",""],
        "ot":["ot$",""],
        chr(244):[chr(244),""],
        "au":["au","aur"],
        "in":["in",""],
        "im":["im",""],
        "ain":["ain",""],
        "aim":["aim",""],
        "ein":["ein",""],
        "yn":["yn",""],
        "ym":["ym",""],
        "ien":["ien",""],
        "un":["un",""],
        "um":["um",""],
        "ien":["ien",""],
        "ien":["ien",""],
        "ien":["ien",""]
    }
